const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('hiraganized', {
  updateSettings: (patch) => ipcRenderer.invoke('app:update-settings', patch),
  hideWindow: () => ipcRenderer.invoke('app:hide-window'),
  minimizeWindow: () => ipcRenderer.invoke('app:minimize-window'),
  maximizeWindow: () => ipcRenderer.invoke('app:maximize-window'),
  onWindowMaximized: (callback) => ipcRenderer.on('window:maximized', (_event, maximized) => callback(maximized)),
  minimizeLogs: () => ipcRenderer.invoke('app:minimize-logs'),
  maximizeLogs: () => ipcRenderer.invoke('app:maximize-logs'),
  onLogsMaximized: (callback) => ipcRenderer.on('logs:maximized', (_event, maximized) => callback(maximized)),
  openLogs: () => ipcRenderer.invoke('app:open-logs'),
  openExternal: (url) => ipcRenderer.invoke('shell:open-external', url),
  onState: (callback) => ipcRenderer.on('app:state', (_event, state) => callback(state)),
  onOcrSetupStart: (callback) => ipcRenderer.on('ocr:setup-start', () => callback()),
  onOcrSetupProgress: (callback) => ipcRenderer.on('ocr:setup-progress', (_event, data) => callback(data)),
  onOcrSetupDone: (callback) => ipcRenderer.on('ocr:setup-done', () => callback()),
  cancelOcrSetup: () => ipcRenderer.invoke('ocr:cancel'),
  getVersion: () => ipcRenderer.invoke('app:get-version'),
  clearDictionaryCache: () => ipcRenderer.invoke('dictionary:clear-cache'),
  resetSettings: () => ipcRenderer.invoke('app:reset-settings'),
  onOcrResult: (callback) => ipcRenderer.on('popup:ocr-result', (_event, text) => callback(text)),
  onPopupPayload: (callback) => ipcRenderer.on('popup:payload', (_event, data) => callback(data)),
  onPopupWarning: (callback) => ipcRenderer.on('popup:warning', (_event, message) => callback(message)),
  resizePopup: (height) => ipcRenderer.send('popup:resize', height),
  commitSelection: (bounds) => ipcRenderer.send('selection:commit', bounds),
  cancelSelection: () => ipcRenderer.send('selection:cancel'),
  onOverlayImage: (callback) => ipcRenderer.on('overlay:image', (_event, frames) => callback(frames)),
  onOverlayReset: (callback) => ipcRenderer.on('overlay:reset', () => callback()),
  onLogLine: (callback) => ipcRenderer.on('logs:line', (_event, line) => callback(line)),
  closeWindow: () => ipcRenderer.send('app:close-logs')
});
